### PR TITLE
update composer.json (psr/simple-cache v2 and v3)

### PR DESCRIPTION
**Pull request by bahramsadin**

### CODE REVIEW

**Comment by codemasher** [comment]
Ha, I completely forgot about this despite the fact that was a PR of mine a couple years ago: https://github.com/php-fig/simple-cache/pull/18. However, since the current version 5.x supports only PHP 8.1+, I'll update it with the according type hints. For v4.x I'll add the version switch as you suggested to allow upgrading.

**Comment by codemasher** [comment]
I'll cherry pick this to v4.x and add type hints for v5.x. Thank you for your contribution!

**Comment by bahramsadin** [comment]
@codemasher 
Could you please release a new version incorporating these changes?
v4.2, v5.1

**Comment by codemasher** [comment]
I just realized that this won't work for v4.x as the updated interfaces would break compatibility when installed under PHP 8+, so I'll leave this one untouched. I'm currently working on upgrading v5.x and will tag it as 5.1 as soon as I'm finished with it.

**Comment by codemasher** [comment]
@bahramsadin I have tagged a new release `5.1.0`. I had to adjust the requirement to `"psr/simple-cache": "^2.0 || ^3.0"` as v1.0 could break compatibility in certain cases (e.g. when a consumer library has 1.0 as the only requirement but would try to install 5.1.x). 

As an implementer I cannot simply specify a version range (an exception in this case is `psr/simple-cache` v2 to v3 as [the only changes between them are return types](https://github.com/php-fig/simple-cache/compare/2.0.0...3.0.0)). On the other hand, a consumer library may specify any version that is able to satisfy the needs, to allow flexibility, e.g. to switch out a library - the specifics of the implementations are not necessarily relevant as long as the interface methods remain compatible.

**Pull request merged**
